<?php

namespace AppBundle\Repository;

/**
 * CinemagiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemagiaRepository extends \Doctrine\ORM\EntityRepository
{
    public function distinctMovie($qb, $link)
    {
        $qb->select('u')
            ->from('AppBundle:Cinemagia','u')
            ->andWhere('u.link = :link')
            ->setParameter('link',$link);
        return $qb;
    }

    public function selectAllMovies($qb)
    {
        $qb->select('u')
            ->from('AppBundle:Cinemagia','u');
        return $qb;
    }

    public function getMovies()
    {
        $qb = $this->createQueryBuilder('u');

        return $qb;
    }

    public function getMoviesByFilters($filterParams)
    {
        $qb = $this->getMovies();
        $qb = $this->addFilters($qb, $filterParams);

        return $qb;
    }

    public function addFilters($qb, $movieFilter)
    {
        if (!(empty($movieFilter['id']))) {
            $qb->andWhere('u.id = :id')
                ->setParameter('id', $movieFilter['id']);
        }
        if (!(empty($movieFilter['title']))) {
        $qb->andWhere('u.title LIKE :title')
            ->setParameter('title', '%'.$movieFilter['title'].'%');
    }

        return $qb;
    }
}
