<?php
/**
 * Created by Sorina Costache.
 * User: sorina
 * Date: 18.04.2017*/

namespace AppBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function distinctLink($qb, $link)
    {
        $qb->select('u')
            ->from('AppBundle:Link','u')
            ->andWhere('u.link = :link')
            ->setParameter('link',$link);
        return $qb;
    }

    public function selectAll($qb)
    {
        $qb->select('u')
            ->from('AppBundle:Link','u');
        return $qb;
    }

}
