<?php

namespace AppBundle\Repository;

/**
 * RottentomatoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RottentomatoesRepository extends \Doctrine\ORM\EntityRepository
{
    public function distinctMovie($qb, $link)
    {
        $qb->select('u')
            ->from('AppBundle:Rottentomatoes','u')
            ->andWhere('u.link = :link')
            ->setParameter('link',$link);
        return $qb;
    }

    public function distinctTitle($qb, $title)
    {
        $qb->select('u')
            ->from('AppBundle:Rottentomatoes','u')
            ->andWhere('u.title = :title')
            ->setParameter('title',$title);
        return $qb;
    }
}
