<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function distinctLink($qb, $link)
    {
        $qb->select('u')
            ->from('AppBundle:Test','u')
            ->andWhere('u.link = :link')
            ->setParameter('link',$link);
        return $qb;
    }

    public function selectAll($qb)
    {
        $qb->select('u')
            ->from('AppBundle:Test','u');
        return $qb;
    }

}
