app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path : /login
    defaults : { _controller: AppBundle:Security:login }

logout:
    path : /logout

home:
    path : /home
    defaults : { _controller: AppBundle:Home:success}

