app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path : /login
    defaults : { _controller: AppBundle:Security:login }

logout:
    path : /logout

home:
    path : /home
    defaults : { _controller: AppBundle:Home:listMovies}

create_account:
    path : /create_account
    defaults : { _controller: AppBundle:Security:createAccount}

default:
    path : /
    defaults : { _controller: AppBundle:Home:listMovies}

crowler:
    path : /crowler
    defaults : { _controller: AppBundle:Home:insertMovies1}

switch_locale:
    path: /switch_locale/{locale}
    defaults: { _controller: AppBundle:Locale:switchLanguage }

add_to_watch:
    path: /home/{id}/watch
    defaults: { _controller: AppBundle:ListToWatch:addToWatch }

want_to_watch:
    path: /want_to_watch
    defaults : { _controller: AppBundle:ListToWatch:listToWatch}