app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path : /login
    defaults : { _controller: AppBundle:Security:login }

logout:
    path : /logout

home:
    path : /home
    defaults : { _controller: AppBundle:Home:listMovies}

create_account:
    path : /create_account
    defaults : { _controller: AppBundle:Security:createAccount}

default:
    path : /
    defaults : { _controller: AppBundle:Home:success}

crowler:
    path : /crowler
    defaults : { _controller: AppBundle:Home:crow}