# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
#        encoders:
#            AppBundle\Entity\User:
#                algorithm:        sha1
#                encode_as_base64: false
#                iterations:       1
        providers:
            our_db_provider:
                entity: { class: AppBundle:User, property: username }
        in_memory:
            memory:

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                default_target_path: default #todo go to dasboard
                remember_me: true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /admin
                domain:   ~ # Defaults to the current domain from $_SERVER
                always_remember_me: false
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER