# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    start_crawler:
        class: AppBundle\Service\StartCrawlerService
        arguments : ["@doctrine.orm.entity_manager"]

    insert_movies:
        class: AppBundle\Service\GetMoviesService
        arguments : ["@doctrine.orm.entity_manager"]
