<?php

namespace AppBundle\Repository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function isDistincMovieInFavorites($qb,$title, $id)
    {
        $qb ->select('u')
            ->from('AppBundle:Favorite','u')
            ->andWhere('u.title = :title and u.user = :id')
            ->setParameter('title',$title)
            ->setParameter('id', $id);

        return $qb;
    }

    public function selectAll($qb, $id)
    {
        $qb->select('u')
            ->from('AppBundle:Favorite','u')
            ->andWhere('u.title is not NULL and u.user = :id')
            ->setParameter('id',$id);

        return $qb;
    }

    public function deleteFromFavorites($qb, $title)
    {
        $qb->select('u')
            ->from('AppBundle:Favorite','u')
            ->andWhere('u.title = :title')
            ->setParameter('title',$title);
        return $qb;
    }

    public function createQuery()
    {
        $qb = $this->createQueryBuilder('u');
        return $qb;
    }

    public function fetchAllFilteredQb($filterParams, $userId)
    {
        $qb = $this->createQuery();
        $qb = $this->addFilters($qb, $filterParams, $userId);
        return $qb;
    }

    public function addFilters($qb, $filterParams, $userId)
    {
        if (!(empty($filterParams['title']))) {
            $qb->andWhere('u.title LIKE :title and u.user = :user')
                ->setParameter('title', '%'.$filterParams['title'].'%')
                ->setParameter('user', $userId);
        }
//        if (isset($filterParams['enabled'])&& $filterParams['enabled']!='All') {
//            $qb->andWhere('u.enabled = :enabled')
//                ->setParameter('enabled', $filterParams['enabled']);
//        }

        if (!(empty($filterParams['rating']))) {
            $qb->andWhere('u.rating = :rating and u.user = :user')
                ->setParameter('rating', $filterParams['rating'])
                ->setParameter('user', $userId);
        }
        return $qb;
    }

}